#!/usr/bin/env dart
// ─────────────────────────────────────────────────────────────────────────────
// scripts/gen_firebase_options.dart
//
// Reads Firebase credentials from the Angular portfolio's .env file and writes
// lib/firebase_options.dart so you don't have to fill it in by hand.
//
// Run from the portfolio-admin directory:
//   dart scripts/gen_firebase_options.dart
//
// The Angular .env file is expected one level up:  ../Angular-Resume/.env
// You can override the path with --env=path/to/.env
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:io';

void main(List<String> args) {
  // ── Locate .env file ────────────────────────────────────────────────────────
  String envPath = '../Angular-Resume/.env';
  for (final arg in args) {
    if (arg.startsWith('--env=')) envPath = arg.substring(6);
  }

  final envFile = File(envPath);
  if (!envFile.existsSync()) {
    stderr.writeln('❌  .env file not found at: $envPath');
    stderr.writeln('   Pass --env=path/to/.env to specify a different path.');
    exit(1);
  }

  // ── Parse key=value pairs ───────────────────────────────────────────────────
  final env = <String, String>{};
  for (final line in envFile.readAsLinesSync()) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
    final idx = trimmed.indexOf('=');
    if (idx < 0) continue;
    env[trimmed.substring(0, idx).trim()] = trimmed.substring(idx + 1).trim();
  }

  // ── Validate required keys ──────────────────────────────────────────────────
  const required = [
    'FIREBASE_API_KEY',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID',
  ];
  final missing = required.where((k) => (env[k] ?? '').isEmpty).toList();
  if (missing.isNotEmpty) {
    stderr.writeln('❌  Missing Firebase keys in .env: ${missing.join(', ')}');
    stderr.writeln('   Fill them in and re-run.');
    exit(1);
  }

  final apiKey            = env['FIREBASE_API_KEY']!;
  final authDomain        = env['FIREBASE_AUTH_DOMAIN'] ?? '';
  final databaseURL       = env['FIREBASE_DATABASE_URL'] ?? '';
  final projectId         = env['FIREBASE_PROJECT_ID']!;
  final storageBucket     = env['FIREBASE_STORAGE_BUCKET'] ?? '';
  final messagingSenderId = env['FIREBASE_MESSAGING_SENDER_ID']!;
  final appId             = env['FIREBASE_APP_ID']!;
  final measurementId     = env['FIREBASE_MEASUREMENT_ID'] ?? '';

  // ── Write firebase_options.dart ─────────────────────────────────────────────
  final out = File('lib/firebase_options.dart');
  out.writeAsStringSync('''
// Generated by scripts/gen_firebase_options.dart — do not edit by hand.
// Re-generate with:  dart scripts/gen_firebase_options.dart
// This file is gitignored — never commit real credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            '$apiKey',
    authDomain:        '$authDomain',
    databaseURL:       '$databaseURL',
    projectId:         '$projectId',
    storageBucket:     '$storageBucket',
    messagingSenderId: '$messagingSenderId',
    appId:             '$appId',
    measurementId:     '$measurementId',
  );

  // Android & iOS share the same project — for a production release,
  // replace appId below with the native app ID from google-services.json /
  // GoogleService-Info.plist (run `flutterfire configure` to generate both).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            '$apiKey',
    appId:             '$appId',
    messagingSenderId: '$messagingSenderId',
    projectId:         '$projectId',
    storageBucket:     '$storageBucket',
    databaseURL:       '$databaseURL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            '$apiKey',
    appId:             '$appId',
    messagingSenderId: '$messagingSenderId',
    projectId:         '$projectId',
    storageBucket:     '$storageBucket',
    databaseURL:       '$databaseURL',
    iosBundleId:       'com.example.portfolioAdmin',
  );
}
''');

  stdout.writeln('✅  lib/firebase_options.dart written for project: $projectId');
}
